PKGROOT		= /opt/cern/root
NAME		= root
VERSION		= 5.34.11
RELEASE		= 1
TARBALL_POSTFIX	= tar.gz

ROOT_NAME = root
ROOT_VERSION=5.34.11

SRC_SUBDIR	= root

TGZ_PKGS = $(ROOT_NAME)_v$(ROOT_VERSION).source.$(TARBALL_POSTFIX)
