PKGROOT		= /opt/cern/clhep
NAME		= clhep
VERSION		= 2.1.3.1
RELEASE		= 0
TARBALL_POSTFIX	= tgz

SRC_SUBDIR	= clhep
CLHEP_NAME  = clhep
CLHEP_VERSION  = 2.1.3.1

TGZ_PKGS = $(CLHEP_NAME)-$(CLHEP_VERSION).$(TARBALL_POSTFIX)
RPM.EXTRAS         = AutoReq:No
