PKGROOT		= /opt/cern/geant
NAME		= geant
VERSION		= 4.9.6.p02
RELEASE		= 1
TARBALL_POSTFIX	= tar.gz

SRC_SUBDIR	= geant
GEANT_NAME  = geant
GEANT_VERSION  = 4.9.6.p02

G4EMLOW_DATA_NAME  = G4EMLOW
G4EMLOW_DATA_VERSION  = 6.32

TGZ_PKGS = $(GEANT_NAME)$(GEANT_VERSION).$(TARBALL_POSTFIX) $(G4EMLOW_DATA_NAME).$(G4EMLOW_DATA_VERSION).$(TARBALL_POSTFIX)
