#%Module1.0
module-whatis "cern applicatons"
module-whatis "Version: VERSION"
module-whatis "Description: cern applications"

prepend-path PATH /opt/cern/root/bin:/opt/cern/geant4/bin:/opt/cern/clhep/bin
prepend-path LD_LIBRARY_PATH /opt/cern/root/lib/root:/opt/cern/geant4/lib64:/opt/cern/clhep/lib/clhep
setenv G4LEDATA /opt/cern/geant4/data
setenv G4NEUTRONHPDATA /opt/cern/geant4/share/Geant4-10.01/data/G4NDL4.5
setenv G4LEDATA /opt/cern/geant4/share/Geant4-10.01/data/G4EMLOW6.41
setenv G4LEVELGAMMADATA /opt/cern/geant4/share/Geant4-10.01/data/PhotonEvaporation3.1
setenv G4RADIOACTIVEDATA /opt/cern/geant4/share/Geant4-10.01/data/RadioactiveDecay4.2
setenv G4NEUTRONXSDATA /opt/cern/geant4/share/Geant4-10.01/data/G4NEUTRONXS1.4
setenv G4PIIDATA /opt/cern/geant4/share/Geant4-10.01/data/G4PII1.3
setenv G4REALSURFACEDATA /opt/cern/geant4/share/Geant4-10.01/data/RealSurface1.0
setenv G4SAIDXSDATA /opt/cern/geant4/share/Geant4-10.01/data/G4SAIDDATA1.1
setenv G4ABLADATA /opt/cern/geant4/share/Geant4-10.01/data/G4ABLA3.0
module load gnu
