#!/bin/bash
/bin/mkdir -m 0755 -p ROOT_PKGROOTMODULEROOT

cat > ROOT_PKGROOTMODULEROOT/VERSION <<END
#%Module1.0
module-whatis "cern applicatons"
module-whatis "Version: VERSION"
module-whatis "Description: cern applications"

prepend-path PATH /opt/cern/root/bin:/opt/cern/geant/bin:/opt/cern/clhep/bin
prepend-path LD_LIBRARY_PATH /opt/cern/root/lib/root:/opt/cern/geant/lib64:/opt/cern/clhep/lib/clhep
setenv G4LEDATA /opt/cern/geant/data
END

chmod 0644  ROOT_PKGROOTMODULEROOT/VERSION

cat > ROOT_PKGROOTMODULEROOT/.version.VERSION <<END
#%Module1.0
set ModulesVersion VERSION
END

(cd ROOT_PKGROOTMODULEROOT; /bin/ln -s .version.VERSION .version )
